#pragma once

namespace app
{
namespace Player
{
#define SPECTRUM_PLAYER_PARAMETER_0B 150.0f // 0xb
#define SPECTRUM_PLAYER_PARAMETER_JUMP_BALL_TIMER 0.12f // 0xc
#define SPECTRUM_PLAYER_PARAMETER_0E 0.29f // 0xe
#define SPECTRUM_PLAYER_PARAMETER_JUMP_INITIAL 125.4f // 0xf
#define SPECTRUM_PLAYER_PARAMETER_JUMP_HOLD 327.0f // 0x10
} // Player
} // app
