// Initial file auto-generated by SymbolsDB.
#pragma once
#include <System/Component/Fsm.h>
#include <csl/math/vector3.h>
#include <csl/ut/bitset.h>
#include <Hedgehog/Base/System/hhObject.h>

namespace app
{
namespace fnd
{
struct SUpdateInfo;
} // fnd

namespace Camera
{
class CCamera;

class CBoostCameraPlugin : public hh::base::CRefCountObject,
    public Object::Fsm<CBoostCameraPlugin>::Type
{
OPENLW_PRIVATE
    // TODO
    csl::math::Vector3 field_0x20;
    float field_0x30;
    float field_0x34;
    float field_0x38;
    csl::ut::Bitset<unsigned char> m_flags;
    // TODO: Is this just alignment? (Almost certainly yeah)
    float field_0x40;
    float field_0x44;
    CCamera* m_camera;
    // TODO

public:
    // SLW (Wii U): 0x02077D60
    // Colors: TODO
    ~CBoostCameraPlugin();

    // SLW (Wii U): 0x02078100
    // Colors: 0x8011b204
    CBoostCameraPlugin(CCamera* param_1);

    // SLW (Wii U): 0x02078204
    // Colors: 0x8011b4e4
    void AddPlugin();

    // SLW (Wii U): 0x0207829C
    // Colors: 0x8011b60c
    void Update(const fnd::SUpdateInfo& param_1);

    // SLW (Wii U): 0x020782F0
    // Colors: 0x8011b694
    void BeginBoost();

    // SLW (Wii U): 0x02078320
    // Colors: 0x8011b6ac
    void EndBoost();

    // SLW (Wii U): 0x02078474
    // Colors: 0x8011b6bc
    void UpdateCameraShake(float param_1, float param_2);

    // SLW (Wii U): 0x02078734
    // Colors: 0x8011b8f4
    void SetBoostCameraParam();

    // SLW (Wii U): 0x0207879C
    // Colors: 0x8011b94c
    bool CheckBoost();

    // SLW (Wii U): 0x020787F0
    // Colors: 0x8011b96c
    void ChangeState(EventFunc state);

    // SLW (Wii U): 0x0207893C
    // Colors: 0x8011ba0c
    StateType StateNoBoost(const EventType& e);

    // SLW (Wii U): 0x02078ADC
    // Colors: 0x8011bb58
    StateType StateBoostBegin(const EventType& e);

    // SLW (Wii U): 0x02078D14
    // Colors: 0x8011bd1c
    StateType StateBoosting(const EventType& e);

    // SLW (Wii U): 0x02078EC0
    // Colors: 0x8011be9c
    StateType StateBoostEnd(const EventType& e);
};
} // Camera
} // app
