// Initial file auto-generated by SymbolsDB.
#pragma once

namespace csl
{
namespace math
{
struct Vector3;
} // math
} // csl

namespace app
{
namespace CMathUtility
{
//LWAPI(0x0207832C, NONE)
void ChangeValueGradually(csl::math::Vector3& param_1, csl::math::Vector3 const& param_2, float param_3, float param_4);

//LWAPI(0x02078854, NONE)
void ChangeValueGradually(float& param_1, float param_2, float param_3, float param_4);

//LWAPI(0x0207889C, NONE)
void ChangeValueD1Gradually(float& param_1, float param_2, float param_3, float param_4, float param_5, float param_6, float param_7);
} // CMathUtility
} // app
