#pragma once

namespace app
{
namespace Player
{
enum ESpectrumPhantomType
{
    SPECTRUM_PHANTOM_TYPE_DRILL,
    SPECTRUM_PHANTOM_TYPE_LASER,
    SPECTRUM_PHANTOM_TYPE_SPIKE,
    SPECTRUM_PHANTOM_TYPE_ROCKET,
    SPECTRUM_PHANTOM_TYPE_FRENZY,
    SPECTRUM_PHANTOM_TYPE_CUBE,
    SPECTRUM_PHANTOM_TYPE_HOVER,
};
} // Player
} // app
